[package]
name = "departure-board"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "departure-board"
path = "src/main.rs"

[dependencies]
devices = { path = "../../crates/devices" }

tokio = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
