[package]
name = "departure-board"
version.workspace = true
edition.workspace = true

[[bin]]
name = "departure-board"
path = "src/main.rs"

[dependencies]
devices = { path = "../../crates/devices" }
appconfig = { workspace = true }

tokio = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }

[lints]
workspace = true
